Repository animal-squad/project-s-FE, pull requests merged in 2024-11, with the labels that each got.

#31 Feat: [Hotfix] .env 및 LoginPage, Sidebar 요청 주소 수정
  .env
  src/Layout/Sidebar.tsx
  src/Pages/LoginPage.tsx
Labels: 기능 추가, 긴급

#32 #29 Feat: FE 정적 호스팅을 위한 nignx.config 및 Dockerfile 작성
  Dockerfile
  nginx.conf
Labels: 기능 추가, 빌드

#33 PR dev to main
  .env
  src/Layout/Sidebar.tsx
  src/Pages/LoginPage.tsx
Labels: 긴급

#35 #34 Fix: Nginx Error Interceptor 누락
  nginx.conf
Labels: 버그 수정

#37 #36 Fix: 404 페이지 intercept 비정상 작동
  nginx.conf
Labels: 버그 수정

#40 CI/CD: Jenkinsfile 추가
  Jenkinsfile
Labels: CI/CD

#41 #38 Feat: Storage > 바구니 명칭 변경 및 Sidebar 버튼 기능 변경
  package-lock.json
  package.json
  public/assets/icons/Bucket_Icon.svg
  public/assets/icons/Bucket_Icon_Bold.svg
  src/App.tsx
  src/Layout/Header.tsx
  src/Layout/Header/BucketHeader.tsx
  src/Layout/Sidebar.tsx
  src/Pages/BucketPage.tsx
  src/Pages/LoginPage.tsx
  src/Pages/MainPage.tsx
  src/components/FolderComponent.tsx
  src/components/FolderList.tsx
  src/custom.d.ts
  src/svg.d.ts
  tsconfig.app.json
  tsconfig.app.tsbuildinfo
  tsconfig.node.json
  tsconfig.node.tsbuildinfo
  tsconfig.tsbuildinfo
  vite.config.ts
Labels: 기능 추가, 디자인 수정

#46 Feat: 에러 페이지 제작
  public/assets/icons/Bucket_Icon_Black.svg
  src/App.tsx
  src/Pages/UnauthorizedPage.tsx
  src/Pages/UnsharedPage.tsx
Labels: 기능 추가

#47 #44 Feat: 바구니 페이지 List View로 변경
  src/components/FolderComponent.tsx
  src/components/FolderComponent_GridView.tsx
  src/components/FolderList.tsx
  src/store/FileIndexStore.ts
Labels: 기능 추가

#49 #48 Feat: 공유 버튼을 누를 시 뜨는 modal 추가
  src/App.tsx
  src/components/FileList_ListView.tsx
  src/components/FolderComponent.tsx
Labels: 기능 추가

#51 Feat: 조회 시 통신 기능 구현
  src/components/FileList_ListView.tsx
Labels: 기능 추가

#53 #52 Feat: 바구니 복사 기능 구현
  src/components/FileList_ListView.tsx
Labels: 기능 추가

#54 Merge Develop to Main
  package-lock.json
  package.json
  public/assets/icons/Bucket_Icon.svg
  public/assets/icons/Bucket_Icon_Black.svg
  public/assets/icons/Bucket_Icon_Bold.svg
  src/App.tsx
  src/Layout/Header.tsx
  src/Layout/Header/BucketHeader.tsx
  src/Layout/Sidebar.tsx
  src/Pages/BucketPage.tsx
  src/Pages/LoginPage.tsx
  src/Pages/MainPage.tsx
  src/Pages/UnauthorizedPage.tsx
  src/Pages/UnsharedPage.tsx
  src/components/FileComponent_ListView.tsx
  src/components/FileList_ListView.tsx
  src/components/FolderComponent.tsx
  src/components/FolderComponent_GridView.tsx
  src/components/FolderList.tsx
  src/custom.d.ts
  src/store/FileIndexStore.ts
  src/svg.d.ts
  tsconfig.app.json
  tsconfig.app.tsbuildinfo
  tsconfig.node.json
  tsconfig.node.tsbuildinfo
  tsconfig.tsbuildinfo
  vite.config.ts
Labels: 기능 추가

#56 Feat: 구글 로그인 정보 받아오기 추가
  index.html
  public/assets/images/Icon_16.svg
  src/Layout/Sidebar.tsx
  src/Pages/LoginPage.tsx
  src/components/FileList_ListView.tsx
  src/store/FileIndexStore.ts
  src/store/userStore.ts
Labels: 기능 추가

#57 Merge Develop to Main
  index.html
  public/assets/images/Icon_16.svg
  src/Layout/Sidebar.tsx
  src/Pages/LoginPage.tsx
  src/components/FileList_ListView.tsx
  src/store/FileIndexStore.ts
  src/store/userStore.ts
Labels: 기능 추가

#59 #58 HotFix: 바구니 호출 API 주소 변경
  src/components/FolderList.tsx
  src/store/FileIndexStore.ts
Labels: 기능 추가, 긴급

#61 #60 Fix: 페이지네이션 수정
  src/components/FileList_ListView.tsx
  src/components/FolderComponent.tsx
  src/store/FileIndexStore.ts
Labels: 긴급, 버그 수정

#63 Fix: Sidebar Notifs 추가
  src/Layout/Sidebar.tsx
Labels: 긴급, 버그 수정

#64 Merge Develop to Main
  src/Layout/Sidebar.tsx
  src/components/FileList_ListView.tsx
  src/components/FolderComponent.tsx
  src/components/FolderList.tsx
  src/store/FileIndexStore.ts
Labels: 기능 추가

#69 #68 CI/CD: Jenkinsfile 수정
  Jenkinsfile
Labels: 버그 수정, CI/CD

#71 #70 Feat: Sidebar Default 변경 및 Landing Page 사진 추가, 개인정보처리방침 페이지 추가
  public/assets/images/Capture_1.png
  public/assets/images/Capture_2.png
  public/assets/images/Capture_3.png
  src/App.tsx
  src/Layout/Sidebar.tsx
  src/Pages/LandingPage.tsx
  src/Pages/PrivacyPolicyPage.tsx
  src/components/FileList_ListView.tsx
  src/store/FileIndexStore.ts
Labels: 기능 추가

#72 Merge Develop to Main
  public/assets/images/Capture_1.png
  public/assets/images/Capture_2.png
  public/assets/images/Capture_3.png
  src/App.tsx
  src/Layout/Sidebar.tsx
  src/Pages/LandingPage.tsx
  src/Pages/PrivacyPolicyPage.tsx
  src/components/FileList_ListView.tsx
  src/store/FileIndexStore.ts
Labels: 기능 추가

#74 #73 Feat: 바구니 삭제 기능 구현
  src/components/FileList_ListView.tsx
Labels: 기능 추가

#78 #75 Feat: 바구니 제목 수정 기능 추가
  src/components/FileList_ListView.tsx
Labels: 기능 추가

#80 #79 Fix: 버킷 삭제 시 리다이렉트 경로 변경 및 로그아웃 시 로직 변경
  src/Layout/Sidebar.tsx
  src/components/FileList_ListView.tsx
Labels: 버그 수정

#81 #77 Feat: 링크 제목 수정 기능 추가
  src/components/FileList_ListView.tsx
Labels: 기능 추가

#83 Feat: axios 요청 시 401 에러 관련 리다이렉션 추가
  src/components/FileList_ListView.tsx
  src/components/FolderComponent.tsx
  src/components/FolderList.tsx
  src/store/FileIndexStore.ts
Labels: 기능 추가

#85 #84 Fix: 랜딩 페이지 가운데 글씨 색상 및 로그인 버튼 위치 조정
  src/Pages/LandingPage.tsx
Labels: 버그 수정

#86 Merge Develop to Main
  src/Layout/Sidebar.tsx
  src/Pages/LandingPage.tsx
  src/components/FileList_ListView.tsx
  src/components/FolderComponent.tsx
  src/components/FolderList.tsx
  src/store/FileIndexStore.ts
Labels: 기능 추가

#88 #87 HotFix: api 요청 주소 수정
  src/components/FileList_ListView.tsx
Labels: 긴급, 버그 수정

#90 #89 HotFix: unauthorized 페이지 오타 수정
  src/components/FileList_ListView.tsx
Labels: 긴급, 버그 수정

#92 #91 Feat: 바구니 내부 table 배치 변경 및 title 수정 바구니뷰로 이전
  src/components/FileList_ListView.tsx
  src/components/FolderComponent.tsx
Labels: 기능 추가

#94 #93 Feat: 랜딩 페이지에서 로그인 여부 체크 및 이동
  src/Pages/LandingPage.tsx
Labels: 기능 추가

#96 Fix: 랜딩 페이지에서 사용자 정보 요청하는 API 오타 수정
  src/Pages/LandingPage.tsx
Labels: 긴급, 버그 수정

#97 #76 Feat: 태그 수정 / 삭제 기능 추가
  package-lock.json
  package.json
  src/components/FileList_ListView.tsx
Labels: 기능 추가

#101 #100 Feat: Sidebar에 홈버튼 추가
  src/Layout/Sidebar.tsx
Labels: 기능 추가

#102 Merge Develop to Main
  package-lock.json
  package.json
  public/assets/icons/Bucket_Icon_Sticker.png
  public/assets/images/Copy_Image.png
  public/assets/images/Extension_Image.png
  public/assets/images/Tag_Image.png
  src/Layout/Sidebar.tsx
  src/Pages/LandingPage.tsx
  src/components/FileList_ListView.tsx
  src/components/FolderComponent.tsx
  src/ui/sticky-scroll-reveal.tsx
  tailwind.config.js
Labels: 기능 추가

#105 Merge Develop to Main
  public/assets/images/Tag_Image.png
  src/Pages/LandingPage.tsx
  src/ui/images-slider.tsx
  src/ui/sticky-scroll-reveal.tsx
Labels: 기능 추가

#107 #106 HotFix: 태그 빈자리 'Borderless' 삭제 및 태그 null로 들어올 시 '기타'태그 부여
  src/Pages/LandingPage.tsx
  src/components/FileList_ListView.tsx
  src/ui/sticky-scroll-reveal.tsx
Labels: 긴급, 버그 수정

#109 #108 Refactor: Dockerfile node base image 변경
  Dockerfile
Labels: 리팩토링, CI/CD

#111 #110 Fix: lottie 삭제 및 종속성 삭제, 로그인 버튼에 구글 이미지 적용
  Dockerfile
  package-lock.json
  package.json
  public/assets/animations/fileAnimation.json
  public/assets/animations/fileAnimation.lottie
  src/Pages/LandingPage.tsx
  src/Pages/LoginPage.tsx
  src/components/FileList_ListView.tsx
  src/ui/sticky-scroll-reveal.tsx
Labels: 기능 추가

#112 Merge Develop to Main
  package-lock.json
  package.json
  public/assets/animations/fileAnimation.json
  public/assets/animations/fileAnimation.lottie
  src/Pages/LandingPage.tsx
  src/Pages/LoginPage.tsx
Labels: 기능 추가

#114 #113 Feat: 로그인 버튼 기존 디자인 + 구글 로그인 버튼 표시 기능 추가
  src/Pages/LandingPage.tsx
Labels: 기능 추가

#115 Merge Develop to Main
  src/Pages/LandingPage.tsx
Labels: 기능 추가

#117 #116 HotFix: sidebar notif 버그 수정
  src/Layout/Sidebar.tsx
Labels: 긴급, 버그 수정

#119 #118 Feat: UI 개선 : 바구니 페이지
  src/App.tsx
  src/Layout/NewHeader.tsx
  src/components/Bucket_GridView.tsx
  src/index.css
  src/ui/Searchbox.tsx
  tailwind.config.js
Labels: 기능 추가
