Repository animal-squad/project-s-FE, pull requests merged in 2024-12, with the labels that each got.

#122 #120 Feat: UI 개선 : 바구니 내부 페이지 #120
  src/App.tsx
  src/components/NewComponent/Bucket_InsideVIew.tsx
  src/components/NewComponent/Bucket_View.tsx
  src/ui/FloatButton.tsx
  src/ui/TagSelect.tsx
Labels: 기능 추가

#125 Feature/#121
  Dockerfile
  Jenkinsfile
  Jenkinsfile.old
Labels: 리팩토링

#127 fix: Jenkinsfile 누락된 내용 추가
  Jenkinsfile
Labels: 리팩토링

#126 #124 Feat: 업데이트된 UI에 기능 추가 : 바구니
  src/Layout/NewHeader.tsx
  src/Layout/Sidebar.tsx
  src/components/FileList_GridView.tsx
  src/components/FolderComponent.tsx
  src/components/FolderList.tsx
  src/components/NewComponent/Bucket_InsideVIew.tsx
  src/store/BucketStore.ts
  src/store/linkStore.ts
Labels: 기능 추가

#130 #129 Feat: App.tsx 렌더링 주소 변경 및 API 통신 주소 변경
  .env
  src/App.tsx
Labels: 기능 추가, 긴급

#133 #132 HotFix: InsideView 명칭 수정
  src/App.tsx
  tsconfig.app.tsbuildinfo
Labels: 긴급

#135 Feature/#134
  Jenkinsfile
Labels: 리팩토링

#137 #136 Fix: tailwind.config.js ESModule, CommonJS간 호환성 오류 수정
  eslint.config.js
  tsconfig.app.tsbuildinfo
Labels: 긴급, 버그 수정

#139 #138 Fix: tailwindcss config file CommonJS -> ES 변경
  tailwind.config.js
Labels: 긴급, 버그 수정

#140 #128 Feat: 업데이트된 UI에 기능 추가 : 링크
  src/App.tsx
  src/components/NewComponent/Bucket_InsideView.tsx
Labels: 기능 추가

#141 #123 Feat: 링크 뷰 / 검색 페이지 추가
  src/App.tsx
  src/Layout/NewHeader.tsx
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Bucket_ViewPage.tsx
  src/Pages/Link_ViewPage.tsx
  src/store/BucketStore.ts
  src/store/searchLinkStore.ts
  src/ui/Searchbox.tsx
  src/ui/TagSelect_Search.tsx
Labels: 기능 추가

#145 #144 Feat: 링크 추가 기능 구현
  src/ui/FloatButton.tsx
Labels: 기능 추가

#147 #146 Feat: 링크 클릭시 URL open 및 조회수 업데이트 기능 추가
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Link_SearchPage.tsx
  src/Pages/Link_ViewPage.tsx
Labels: 기능 추가

#149 #148 Feat: 프로필 사진 클릭시 메뉴 추가 및 로그아웃 추가
  src/Layout/NewHeader.tsx
Labels: 기능 추가

#152 #151 Feat: 링크 / 바구니 제목 모달에서 Enter 키로 submit 가능하도록 수정
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Link_SearchPage.tsx
  src/Pages/Link_ViewPage.tsx
Labels: 기능 추가

#153 merge Develop to Main
  src/App.tsx
  src/Layout/NewHeader.tsx
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Bucket_ViewPage.tsx
  src/Pages/Link_SearchPage.tsx
  src/Pages/Link_ViewPage.tsx
  src/store/BucketStore.ts
  src/store/LinkSearchStore.ts
  src/store/TagSearchStore.ts
  src/ui/FloatButton.tsx
  src/ui/Searchbox.tsx
  src/ui/TagSelect_Search.tsx
Labels: 기능 추가

#155 #154 Fix: Header 유저 정보 fetch 코드 작성
  src/Layout/NewHeader.tsx
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Bucket_ViewPage.tsx
  src/Pages/LandingPage.tsx
  src/Pages/LoginPage.tsx
Labels: 버그 수정

#156 feat: Test 서버 전용 Jenkinsfile 추가
  Jenkinsfile_test_server
Labels: 기능 추가, CI/CD

#159 fix: Jenkinsfile 수정
  Jenkinsfile_test_server
Labels: 버그 수정

#162 Fix: 검색 요청이 5000개 가는 버그 수정
  src/store/LinkSearchStore.ts
  src/ui/Searchbox.tsx
Labels: 버그 수정

#167 feat: Test 서버 전용 .env 파일 추가 및 Jenkinsfile 수정
  .env.test
  Jenkinsfile_test_server
Labels: 기능 추가, 버그 수정, 빌드

#168 Feature/#166
  Jenkinsfile
  package.json
Labels: 버그 수정

#169 fix: Jenkinsfile 수정
  Jenkinsfile_test_server
Labels: 버그 수정

#170 fix: Jenkinsfile 수정
  Jenkinsfile_test_server
Labels: 버그 수정

#171 fix: package.json 수정
  package.json
Labels: 버그 수정

#172 fix: Jenkinsfile 수정
  Jenkinsfile_test_server
Labels: 버그 수정

#165 Feat: search URL에 query 추가
  src/Pages/Link_SearchPage.tsx
  src/ui/Searchbox.tsx
Labels: 기능 추가

#174 #173 Feat: 디테일 추가
  src/Pages/Bucket_ViewPage.tsx
  src/ui/Searchbox.tsx
  src/ui/TagSelect_Search.tsx
Labels: 기능 추가

#176 Fix: change dto format to link delete API routing
  src/Pages/Link_SearchPage.tsx
  src/Pages/Link_ViewPage.tsx
Labels: 버그 수정

#178 #177 Fix: 링크 태그 조회 라우터 수정
  src/store/TagSearchStore.ts
Labels: 버그 수정

#180 #179 Fix: 바구니 내부 페이지 공유, 제목 수정 버그 수정
  src/Pages/Bucket_InsidePage.tsx
Labels: 버그 수정

#182 #163 Refactor: 검색 기능 리팩토링 #163
  .env.test
  Jenkinsfile
  Jenkinsfile_test_server
  package.json
  src/Pages/Bucket_ViewPage.tsx
  src/Pages/Link_SearchPage.tsx
  src/ui/Searchbox.tsx
  src/ui/TagSelect_Search.tsx
Labels: 리팩토링

#185 #184 Fix: 검색 시 요청 1번만 가도록 수정
  src/Pages/Link_SearchPage.tsx
Labels: 버그 수정

#187 #186 Fix: 전체 선택 0개시 체크 해제 / 바구니 페이지 페이지네이션 확인
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Bucket_ViewPage.tsx
  src/Pages/Link_SearchPage.tsx
  src/Pages/Link_ViewPage.tsx
  src/store/BucketStore.ts
  src/store/LinkSearchStore.ts
  src/store/TagSearchStore.ts
Labels: 버그 수정

#189 #188 Fix: link API 요청 시 요청 많이 가는 버그 수정 + 더미데이터 삭제 #188
  src/Pages/Link_ViewPage.tsx
  src/store/TagSearchStore.ts
  src/ui/FloatButton.tsx
Labels: 버그 수정

#191 #190 Fix: 검색 버그 수정
  src/Pages/Link_SearchPage.tsx
Labels: 버그 수정

#192 Merge Develop to Main
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Bucket_ViewPage.tsx
  src/Pages/Link_SearchPage.tsx
  src/Pages/Link_ViewPage.tsx
  src/store/BucketStore.ts
  src/store/LinkSearchStore.ts
  src/store/TagSearchStore.ts
  src/ui/FloatButton.tsx
Labels: 기능 추가

#194 #193 Fix: 링킷 아이콘 추가 및 메인 페이지로 이동 추가 #193
  public/assets/images/Bucket_Image.webp
  src/Layout/NewHeader.tsx
  src/Pages/Bucket_ViewPage.tsx
Labels: 기능 추가

#195 Merge Develop to Main
  public/assets/images/Bucket_Image.webp
  src/Layout/NewHeader.tsx
  src/Pages/Bucket_ViewPage.tsx
Labels: 기능 추가

#197 #196 Feat: Landing Page에 Chrome extension 설치 페이지 추가
  src/Pages/LandingPage.tsx
Labels: 기능 추가

#199 #198 Fix: 공유 모달 내에서 isPublic 상태를 제대로 받아오지 못하는 버그 수정
  src/Pages/Bucket_InsidePage.tsx
Labels: 버그 수정

#200 #198 Fix: 공유 모달 내에서 isPublic 상태를 제대로 받아오지 못하는 버그 수정
  src/Pages/Bucket_InsidePage.tsx
Labels: 버그 수정

#202 #201 Fix: 항목 수에 따라 페이지 길이가 변동되도록 수정
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Bucket_ViewPage.tsx
  src/Pages/Link_SearchPage.tsx
  src/Pages/Link_ViewPage.tsx
  src/store/linkStore.ts
Labels: 버그 수정

#205 #204 Fix: 링크 삭제 요청 수정
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Link_SearchPage.tsx
Labels: 버그 수정

#206 Fix: 링크 삭제 요청 수정
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Link_SearchPage.tsx
Labels: 버그 수정

#207 Merge to Develop
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Link_SearchPage.tsx
Labels: 버그 수정

#209 #208 Fix: Unauthorized 페이지 이전 페이지 -> 바구니 페이지 수정
  src/Pages/UnsharedPage.tsx
Labels: 버그 수정

#211 #210 Fix: 에러 페이지 배경색 변경
  src/Pages/UnauthorizedPage.tsx
  src/Pages/UnsharedPage.tsx
Labels: 버그 수정

#212 Merge Develop to Main
  src/Pages/UnauthorizedPage.tsx
  src/Pages/UnsharedPage.tsx
Labels: 기능 추가

#214 #213 Fix: 복사 로직 수정 후 모달 닫기 추가
  src/Pages/Bucket_InsidePage.tsx
Labels: 버그 수정

#215 Merge Develop to Main
  src/Pages/Bucket_InsidePage.tsx
Labels: 버그 수정

#217 #216 Fix: Landing Page Header z-index 수정
  src/Pages/LandingPage.tsx
Labels: 버그 수정

#219 #218 Fix: 전체 선택 오류 수정
  src/Pages/Bucket_InsidePage.tsx
  src/Pages/Link_SearchPage.tsx
  src/Pages/Link_ViewPage.tsx
Labels: 버그 수정

#221 #220 Fix: 단일 링크 추가 수정
  src/ui/FloatButton.tsx
Labels: 버그 수정

#224 #223 Fix: 단일 링크 추가 로직 변경
  src/ui/FloatButton.tsx
Labels: 버그 수정

#225 Merge Develop to Main
  src/ui/FloatButton.tsx
Labels: 버그 수정
